default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kaigi_development

test:
  <<: *default
  database: kaigi_test

production:
  <<: *default
  database: kaigi_production